name: pipeSEC
on:
  workflow_dispatch:
  
jobs:
  scanImage:
    name: Start Docker Trivy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t openjdk
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'openjdk:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
  build:
    runs-on: ubuntu-latest
    needs: scanImage
    steps:
    - name: Rodando o Build
      run: echo Build deu bom
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build
    steps:
    - name: Rodando o Deploy DEV
      run: echo Deploy DEV deu bom
  
  deploy-sast:
    runs-on: ubuntu-latest
    environment:
      name: sast
    needs: build
    steps:
    - name: Rodando o HoruSec
      run: |
          sudo apt-get install git -y
          git clone https://github.com/crypto-br/demoSecurityPipeline.git
          cd demoSecurityPipeline
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash
          horusec start -p="./" 
  
  deploy-hml:
    runs-on: ubuntu-latest
    environment:
      name: hml
      url: 'https://google.com.br'
    needs: [deploy-dev, deploy-sast]
    steps:
    - name: Rodando o Deploy HML
      run: echo Deploy HML deu bom
    
  deploy-dast:
    runs-on: ubuntu-latest
    environment:
      name: dast
    needs: deploy-hml
    steps:
    - name: Rodando o OWASP ZAP
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'https://google.com.br'
    
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: [deploy-hml, deploy-dast]
    steps:
    - name: Rodando o Deploy PRD
      run: echo Deploy PRD deu bom
